### ISSUE TITLE
Migrate away from wordpress

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/AtlassianPS#3]
In a conversation with https://github.com/TomasDeceuninck, it was suggested to use jekyll for our documentation/homepage.

I am quite fond of that idea. 
### My suggestion
* create a new repo: `AtlassianPS.github.io`
* this repo would contain the html files for our homepage
* new articles would have to be created there (in `.md`)
* documentation could be shown from the other modules
* repo can contain own documentation (eg: how to contribute) that would be shared across all modules
* the registered domain can be CNAME to the github page

### Downside
* No user registration
* No control over the access & co (google analytics should still work)
* Look and feel of homepage has to be coded and committed to repo
* No Database
* No plugins
* No slack inviter in our domain

### Example
https://invoke-automation.github.io/Invoke-Documentation/projects/AtlassianCLI/README

### Meta
To: @brianbunke 
CC: @beaudryj , @replicaJunction , @AtlassianPS/maintainers , @AtlassianPS/moderators , @AtlassianPS/reviewers

**Comment by brianbunke** [comment]
It's not vital, but it seems like a pretty good idea.

[My blog](https://github.com/brianbunke/brianbunke.github.io) is also running on GitHub Pages. Google Analytics still works, but yeah, you don't have the vast plugin ecosystem of WordPress. (Which is good and bad, really.)

Unless you have a really specific use case, I don't miss user registration or a database to maintain.

You can CNAME, but GHP doesn't currently support https for custom domains. Small thing, but FYI.

It's really important to be able to preview Jekyll locally, so you don't make ten commits trying to screw with CSS like I was at the beginning. ([Shameless plug](http://www.brianbunke.com/blog/2017/05/24/jekyll-win10/) for setting up Jekyll on Win10.)

The big thing will just be finding a theme that works. Again, there are a million more options on the WordPress side.

**Comment by tms-d** [comment]
Seting it up localy is easy enough.
I followed the guide on https://jekyllrb.com/docs/windows/
And its always a good thing to include a TL;DR in the readme with basic instructions.

**Comment by beaudryj** [comment]
meh I dont get the need for the fancy overhead of a DB and logins I like the simplicity of GHP docs, as for the slack invites and whatnot maybe setup an azurefunction or something to send the slack invite or maybe there are some otherways to get the automated invites.

**Comment by ebekker** [comment]
You can auto-generate the API reference docs with [DocTreeGenerator](https://github.com/msorens/DocTreeGenerator).

[Here](https://zyborg.github.io/Zyborg.Vault/docs/api/Zyborg/Zyborg.Vault/index.html) is an example of a project where I used it.  You can customize the template to match whatever look and feel you want.

**Comment by ebekker** [comment]
Disregard my last comment just saw you were talking about using PlatyPS in another ticket.
