### ISSUE TITLE
New Module: ConfluenceTools

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/AtlassianPS#8]
From where I stand, [ConfluencePS](https://github.com/AtlassianPS/ConfluencePS) should:
* [x] provide the means for a user to interact with the Confluence system **✓**
* [ ] provide the tools to make the content of the page look pretty **✗**

My proposition is, to remove all functions for manipulating the content of pages from the module and moving them to a new place. These functions are:
* [ConvertTo-Table](https://github.com/AtlassianPS/ConfluencePS/blob/master/ConfluencePS/Public/ConvertTo-Table.ps1)

This new place could be a module (eg: `ConfluenceTools`), which is recommend for `ConfluencePS`; but not mandatory.
This new module could also include function for creating macros (eg: `New-JiraMacro`).

This new module would be part of the `AtlassianPS` module.

**Comment by brianbunke** [comment]
Today, I don't think this should happen. There's not enough to move in there that warrants the added level of complexity, in my opinion.

That said, macro handling in page bodies right now suuucks (like, RegEx string replacement level of suck), and abstracting that behavior would be welcome.

If macro functions then started getting specific to macros, that would clutter up the base module, and there would definitely be a point where it would make sense to break it off.

There's also an argument of "everything except `ConvertTo-Table` (and proposed macro functionality) needs to interact with the server/API."

I'm not opposed to this idea. I just think I would need to see more before the complexity is introduced.

**Comment by lipkau** [comment]
Agreed!

Let'S revisit this once it's cluttering the ConfluencePS module :-)
